### ISSUE TITLE
Время для проверки свободных мест

### ISSUE THREAD

**Issue by Vladislavik** [kazatca/midpass_bot#1]
Добрый день, а в какое время обычно появляются места для записи? Есть ли инструкция как бота запустить?

**Comment by kazatca** [comment]
Привет

> В какое время обычно появляются места для записи?

Не знаю. Бот подтверждает актуальность записи в _листе ожидания_. Когда очередь доходит до нее, вас добавляют в расписание в первый свободный слот без возможности выбрать дату и время.
 
> Есть ли инструкция как бота запустить?

Пока не планировал документировать. У q.midpass.ru какие-то жлобские rate-limit-ы, при превышении которых пользователь банится на час и сбрасывается пароль. Т.е. вреда от бота может быть больше чем пользы
